### ISSUE TITLE
Search for random levels with filters!

### ISSUE THREAD

**Issue by rubiidev18alt** [Alphalaneous/Random-Tab#1]
so basically, if I want random challenges, I put insane as the diff and put "challenge" in the search bar, but, when I do that, it does the random levels without filters! pls do that,

(also, I made a fork for this that adds the github in the info)

#2

**Comment by Alphalaneous** [comment]
I cannot add filters due to the requirement of trying to find a random level of each difficulty needing multiple requests to the servers. Due to that, it could yield IP bans or would require multiple minutes of loading which is not ideal.

**Comment by rubiidev18alt** [comment]
> I cannot add filters due to the requirement of trying to find a random level of each difficulty needing multiple requests to the servers. Due to that, it could yield IP bans or would require multiple minutes of loading which is not ideal.

maybe there's a way to do it, but without trouble from rate limiting/faster
